// Do not edit. This file is machine generated by the Resource DLL Wizard.

library Project1;

{ITE} {DFMFileType} {Cjepljenje.dfm}
{ITE} {DFMFileType} {Unit10.dfm}
{ITE} {DFMFileType} {Unit11.dfm}
{ITE} {DFMFileType} {Unit12.dfm}
{ITE} {DFMFileType} {Unit2.dfm}
{ITE} {DFMFileType} {Unit3.dfm}
{ITE} {DFMFileType} {Unit5.dfm}
{ITE} {DFMFileType} {Unit6.dfm}
{ITE} {DFMFileType} {Unit7.dfm}
{ITE} {RCFileType} {Project1_DRC.rc}

{$R 'Cjepljenje.dfm' 'Form1:TForm'}
{$R 'Unit10.dfm' 'Form10:TForm'}
{$R 'Unit11.dfm' 'Form11:TForm'}
{$R 'Unit12.dfm' 'Form12:TForm'}
{$R 'Unit2.dfm' 'Form2:TForm'}
{$R 'Unit3.dfm' 'Form3:TForm'}
{$R 'Unit5.dfm' 'Form5:TForm'}
{$R 'Unit6.dfm' 'Form6:TForm'}
{$R 'Unit7.dfm' 'Form7:TForm'}
{$R 'Project1_DRC.res' 'Project1_DRC.rc'}

{$E HRV}

begin
end.
